# Site Info
title: "sebeom"
tagline: "sebeom"
description: 'sebeom'
baseurl: ''
url: http://znznz6037.github.io
logo: '/public/favicon.png'

# Site configurations
gems:
  - jekyll-paginate
  - jemoji
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 1
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.1.0

# About/contact
author: 
  name: znznz6037
  description: <a href="https://programmers.co.kr/pr/znznz6037">Hello!</a> üèñ
  gravatar:  6681f478d666f7cb51fe7bf6e93242bf # md5 hash of your email address
  contact:
    github:    https://github.com/znznz6037
    #instagram: https://instagram.com/_sebeom

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
#  About:          
#    - 'https://programmers.co.kr/pr/znznz6037'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/we_will_be_giants_by_yalestewart.jpg
  caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'your_short_names' # leave blank if you don't want disqus

#
future: true