# Site Info
title: "메모장"
tagline: "메모장"
description: ''
baseurl: ''
url: http://znznz6037.github.io
logo: '/public/favicon.png'

# Site configurations
gems:
  - jekyll-paginate
  - jemoji
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 1
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.1.0

# About/contact
author: 
  name: znznz6037
  description: 
  gravatar:  6681f478d666f7cb51fe7bf6e93242bf # md5 hash of your email address
  contact:
    github:    https://github.com/znznz6037
    #instagram: https://instagram.com/_sebeom

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    #- { Tags: '/blog/tags/' }
#  About:          
#    - 'https://programmers.co.kr/pr/znznz6037'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/dev_jeans.png
  caption: Original Artwork &copy; <a href="https://velog.io/@heelieben/님들이-만들어쓰는-개발진스">@dev_hee</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'your_short_names' # leave blank if you don't want disqus

#
future: true